// Generated by ReScript, PLEASE EDIT WITH CARE


function toShape(n) {
  if (n !== 1) {
    if (n !== 2) {
      return "Pill";
    } else {
      return "Diamond";
    }
  } else {
    return "Tilde";
  }
}

function toColor(n) {
  if (n !== 1) {
    if (n !== 2) {
      return "Purple";
    } else {
      return "Green";
    }
  } else {
    return "Red";
  }
}

function toFill(n) {
  if (n !== 1) {
    if (n !== 2) {
      return "Outlined";
    } else {
      return "Striped";
    }
  } else {
    return "Solid";
  }
}

function toNumber(n) {
  if (n !== 1) {
    if (n !== 2) {
      return "Three";
    } else {
      return "Two";
    }
  } else {
    return "One";
  }
}

function fromNumber(n) {
  switch (n) {
    case "One" :
      return 1;
    case "Two" :
      return 2;
    case "Three" :
      return 3;
  }
}

export {
  toShape,
  toColor,
  toFill,
  toNumber,
  fromNumber,
}
/* No side effect */
