// Generated by ReScript, PLEASE EDIT WITH CARE


function make(pointsOpt, errorsOpt, winsOpt) {
  let points = pointsOpt !== undefined ? pointsOpt : 0;
  let errors = errorsOpt !== undefined ? errorsOpt : 0;
  let wins = winsOpt !== undefined ? winsOpt : 0;
  return {
    points: points,
    errors: errors,
    wins: wins
  };
}

function hit(score) {
  return make(score.points + 1 | 0, score.errors, score.wins);
}

function miss(score) {
  return make(score.points, score.errors + 1 | 0, score.wins);
}

function win(score) {
  return make(score.points, score.errors, score.wins + 1 | 0);
}

let Score = {
  make: make,
  hit: hit,
  miss: miss,
  win: win
};

function change(mode) {
  if (mode.TAG === "AI") {
    return {
      TAG: "Zen",
      _0: mode._1
    };
  }
  let score = mode._0;
  return {
    TAG: "AI",
    _0: score,
    _1: score
  };
}

let Mode = {
  change: change
};

function make$1(mode, gameTime) {
  return {
    mode: mode,
    gameTime: gameTime,
    state: "Playing"
  };
}

function pause(state) {
  return {
    mode: state.mode,
    gameTime: state.gameTime,
    state: "Paused"
  };
}

function validate(state) {
  return {
    mode: state.mode,
    gameTime: state.gameTime,
    state: {
      TAG: "Validating",
      _0: make(undefined, undefined, undefined)
    }
  };
}

let State = {
  make: make$1,
  pause: pause,
  validate: validate
};

function start(mode, gameTime) {
  return {
    mode: mode,
    gameTime: gameTime,
    state: "Playing"
  };
}

export {
  Score,
  Mode,
  State,
  start,
}
/* No side effect */
