// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";

function areSame(property) {
  switch (property) {
    case "Shape" :
      return (a, b) => a.shape === b.shape;
    case "Color" :
      return (a, b) => a.color === b.color;
    case "Fill" :
      return (a, b) => a.fill === b.fill;
    case "Number" :
      return (a, b) => a.number === b.number;
  }
}

let areShapesSame = areSame("Shape");

let areColorsSame = areSame("Color");

let areFillsSame = areSame("Fill");

let areNumbersSame = areSame("Number");

function init() {
  return /* [] */0;
}

let ListCollection = {
  length: Stdlib_List.length,
  add: Stdlib_List.add,
  map: Stdlib_List.map,
  toArray: Stdlib_List.toArray,
  init: init
};

function MakeGameSet(C) {
  return Collection => {
    let maybeSet = cards => {
      let match = Collection.length(cards);
      if (match !== 0) {
        if (match !== 3) {
          return {
            TAG: "Filling",
            _0: cards
          };
        } else {
          return {
            TAG: "Filled",
            _0: cards
          };
        }
      } else {
        return "Empty";
      }
    };
    let add = (cards, card) => {
      let match = Collection.length(cards);
      if (match !== 3) {
        return Collection.add(cards, card);
      } else {
        return cards;
      }
    };
    return {
      length: Collection.length,
      map: Collection.map,
      toArray: Collection.toArray,
      make: Collection.init,
      maybeSet: maybeSet,
      add: add
    };
  };
}

function maybeSet(cards) {
  let match = Stdlib_List.length(cards);
  if (match !== 0) {
    if (match !== 3) {
      return {
        TAG: "Filling",
        _0: cards
      };
    } else {
      return {
        TAG: "Filled",
        _0: cards
      };
    }
  } else {
    return "Empty";
  }
}

function add(cards, card) {
  let match = Stdlib_List.length(cards);
  if (match !== 3) {
    return Stdlib_List.add(cards, card);
  } else {
    return cards;
  }
}

let GameSet = {
  length: Stdlib_List.length,
  map: Stdlib_List.map,
  toArray: Stdlib_List.toArray,
  make: init,
  maybeSet: maybeSet,
  add: add
};

export {
  areSame,
  areShapesSame,
  areColorsSame,
  areFillsSame,
  areNumbersSame,
  ListCollection,
  MakeGameSet,
  GameSet,
}
/* areShapesSame Not a pure module */
