// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Deck from "../play/Deck.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function init() {
  return /* [] */0;
}

let ListCollection = {
  length: Stdlib_List.length,
  add: Stdlib_List.add,
  map: Stdlib_List.map,
  toArray: Stdlib_List.toArray,
  init: init
};

function MakeGameSet(C) {
  return Collection => {
    let inspect = (cards, messageOpt) => {
      let message = messageOpt !== undefined ? messageOpt : "Cards";
      console.log(message, cards);
      return cards;
    };
    let maybeSet = cards => {
      let match = Collection.length(cards);
      if (match !== 0) {
        if (match !== 3) {
          return {
            TAG: "Filling",
            _0: cards
          };
        } else {
          return {
            TAG: "Filled",
            _0: cards
          };
        }
      } else {
        return "Empty";
      }
    };
    let add = (cards, card) => {
      let match = Collection.length(cards);
      if (match !== 3) {
        return Collection.add(cards, card);
      } else {
        return cards;
      }
    };
    let toSet = (s, _l) => {
      while (true) {
        let l = _l;
        if (l === 0) {
          return s;
        }
        s.add(l.hd);
        _l = l.tl;
        continue;
      };
    };
    let checkProperty = (getProperty, cards) => {
      let values = toSet(new Set(), Stdlib_List.map(cards, getProperty));
      let match = values.size;
      if (match !== 1 && match !== 3) {
        return "Invalid";
      } else {
        return "Valid";
      }
    };
    let checkShapes = extra => checkProperty(card => card.shape, extra);
    let checkColors = extra => checkProperty(card => card.color, extra);
    let checkFills = extra => checkProperty(card => card.fill, extra);
    let checkNumbers = extra => checkProperty(card => card.number, extra);
    return {
      length: Collection.length,
      map: Collection.map,
      toArray: Collection.toArray,
      make: Collection.init,
      inspect: inspect,
      maybeSet: maybeSet,
      add: add,
      toSet: toSet,
      checkProperty: checkProperty,
      checkShapes: checkShapes,
      checkColors: checkColors,
      checkFills: checkFills,
      checkNumbers: checkNumbers
    };
  };
}

function inspect(cards, messageOpt) {
  let message = messageOpt !== undefined ? messageOpt : "Cards";
  console.log(message, cards);
  return cards;
}

function maybeSet(cards) {
  let match = Stdlib_List.length(cards);
  if (match !== 0) {
    if (match !== 3) {
      return {
        TAG: "Filling",
        _0: cards
      };
    } else {
      return {
        TAG: "Filled",
        _0: cards
      };
    }
  } else {
    return "Empty";
  }
}

function add(cards, card) {
  let match = Stdlib_List.length(cards);
  if (match !== 3) {
    return Stdlib_List.add(cards, card);
  } else {
    return cards;
  }
}

function toSet(s, _l) {
  while (true) {
    let l = _l;
    if (l === 0) {
      return s;
    }
    s.add(l.hd);
    _l = l.tl;
    continue;
  };
}

function checkProperty(getProperty, cards) {
  let values = toSet(new Set(), Stdlib_List.map(cards, getProperty));
  let match = values.size;
  if (match !== 1 && match !== 3) {
    return "Invalid";
  } else {
    return "Valid";
  }
}

function checkShapes(extra) {
  return checkProperty(card => card.shape, extra);
}

function checkColors(extra) {
  return checkProperty(card => card.color, extra);
}

function checkFills(extra) {
  return checkProperty(card => card.fill, extra);
}

function checkNumbers(extra) {
  return checkProperty(card => card.number, extra);
}

let GameSet = {
  length: Stdlib_List.length,
  map: Stdlib_List.map,
  toArray: Stdlib_List.toArray,
  make: init,
  inspect: inspect,
  maybeSet: maybeSet,
  add: add,
  toSet: toSet,
  checkProperty: checkProperty,
  checkShapes: checkShapes,
  checkColors: checkColors,
  checkFills: checkFills,
  checkNumbers: checkNumbers
};

function test() {
  let deck = Belt_Array.shuffle(Deck.init());
  console.log("Deck", deck);
  let cards = deck.slice(0, 3);
  Stdlib_Array.reduce([
    0,
    1,
    2
  ], init(), (set, i) => {
    let __x = maybeSet(set);
    console.log("Status", __x);
    let s = add(set, Stdlib_Option.getOrThrow(cards[i], undefined));
    let status = maybeSet(s);
    if (typeof status !== "object") {
      console.log("Set empty");
    } else if (status.TAG === "Filling") {
      console.log("Set filling", status._0);
    } else {
      console.log("Set filled", status._0);
    }
    return s;
  });
  let listCards = Stdlib_List.fromArray(cards);
  let checkFns = [
    [
      "Shapes",
      checkShapes
    ],
    [
      "Colors",
      checkColors
    ],
    [
      "Fills",
      checkFills
    ],
    [
      "Numbers",
      checkNumbers
    ]
  ];
  checkFns.map(param => [
    param[0],
    param[1](listCards)
  ]).forEach(param => {
    console.log("Check", param[0], param[1]);
  });
}

export {
  ListCollection,
  MakeGameSet,
  GameSet,
  test,
}
/* No side effect */
