// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";

function init() {
  return /* [] */0;
}

let ListCollection = {
  length: Stdlib_List.length,
  add: Stdlib_List.add,
  map: Stdlib_List.map,
  toArray: Stdlib_List.toArray,
  init: init
};

function MakeGameSet(C) {
  return Collection => {
    let maybeSet = cards => {
      let match = Collection.length(cards);
      return match === 3;
    };
    let add = (cards, card) => {
      let match = Collection.length(cards);
      if (match !== 3) {
        return Collection.add(cards, card);
      } else {
        return cards;
      }
    };
    return {
      length: Collection.length,
      map: Collection.map,
      toArray: Collection.toArray,
      make: Collection.init,
      maybeSet: maybeSet,
      add: add
    };
  };
}

function maybeSet(cards) {
  let match = Stdlib_List.length(cards);
  return match === 3;
}

function add(cards, card) {
  let match = Stdlib_List.length(cards);
  if (match !== 3) {
    return Stdlib_List.add(cards, card);
  } else {
    return cards;
  }
}

let GameSet = {
  length: Stdlib_List.length,
  map: Stdlib_List.map,
  toArray: Stdlib_List.toArray,
  make: init,
  maybeSet: maybeSet,
  add: add
};

export {
  ListCollection,
  MakeGameSet,
  GameSet,
}
/* No side effect */
