// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Time from "./Time.res.mjs";
import * as React from "react";
import * as Button from "../Button.res.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as JsxRuntime from "react/jsx-runtime";

function CallSetButton(props) {
  let onClick = props.onClick;
  let text = props.text;
  let match = React.useState(() => {});
  let setCountdown = match[1];
  let match$1 = React.useState(() => text);
  let setButtonText = match$1[1];
  let handleClick = event => {
    onClick(event);
    setCountdown(param => 10);
  };
  let onCountdownDecrement = timeRemaining => {
    setButtonText(param => {
      if (timeRemaining !== undefined) {
        return timeRemaining.toString();
      } else {
        return text;
      }
    });
    if (Primitive_object.equal(timeRemaining, 0)) {
      setCountdown(param => {});
      return setButtonText(param => "SET!");
    }
  };
  Time.useCountdown(match[0], setCountdown, onCountdownDecrement);
  return JsxRuntime.jsx(Button.make, {
    children: match$1[0],
    onClick: handleClick
  });
}

let make = CallSetButton;

export {
  make,
}
/* Time Not a pure module */
