// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function getColorValue(color) {
  switch (color) {
    case "Red" :
      return "hsl(0, 100%, 45%)";
    case "Green" :
      return "hsl(120, 100%, 25%)";
    case "Purple" :
      return "hsl(300, 100%, 25%)";
  }
}

function getColor(card) {
  return getColorValue(card.color);
}

function colorToString(color) {
  switch (color) {
    case "Red" :
      return "red";
    case "Green" :
      return "green";
    case "Purple" :
      return "purple";
  }
}

function getPatternId(card) {
  return "stripes-" + colorToString(card.color);
}

function getFillAttrs(card) {
  let color = getColorValue(card.color);
  let match = card.fill;
  switch (match) {
    case "Solid" :
      return {
        fill: color,
        stroke: "none",
        strokeWidth: "0"
      };
    case "Striped" :
      return {
        fill: "url(#" + getPatternId(card) + ")",
        stroke: color,
        strokeWidth: "0.3"
      };
    case "Outlined" :
      return {
        fill: "none",
        stroke: color,
        strokeWidth: "0.3"
      };
  }
}

function Icon$Diamond(props) {
  return JsxRuntime.jsx("svg", {
    children: JsxRuntime.jsx("polygon", {
      fill: props.fill,
      points: "1,4 6,7 11,4 6,1",
      stroke: props.stroke,
      strokeWidth: props.strokeWidth
    }),
    viewBox: "0 0 12 8",
    xmlns: "http://www.w3.org/2000/svg",
    xmlnsXlink: "http://www.w3.org/1999/xlink"
  });
}

let Diamond = {
  make: Icon$Diamond
};

function Icon$Pill(props) {
  return JsxRuntime.jsx("svg", {
    children: JsxRuntime.jsx("path", {
      d: "M3,2h6c1.1,0,2,0.9,2,2v0c0,1.1-0.9,2-2,2H3C1.9,6,1,5.1,1,4v0C1,2.9,1.9,2,3,2z",
      fill: props.fill,
      stroke: props.stroke,
      strokeWidth: props.strokeWidth
    }),
    viewBox: "0 0 12 8",
    xmlns: "http://www.w3.org/2000/svg",
    xmlnsXlink: "http://www.w3.org/1999/xlink"
  });
}

let Pill = {
  make: Icon$Pill
};

function Icon$Tilde(props) {
  return JsxRuntime.jsx("svg", {
    children: JsxRuntime.jsx("path", {
      d: "M2,6.3C1.4,6.3,0.9,6,0.5,5.5C0,4.7,0.2,3.6,1,3c1.9-1.3,4-1.7,6-0.6c0.7,0.4,1.3,0.2,1.9-0.3c0.7-0.6,1.8-0.5,2.5,0.2\n                c0.6,0.7,0.5,1.8-0.2,2.5C9.4,6.3,7.3,6.6,5.3,5.5C4.5,5.1,3.7,5.4,3,6C2.7,6.2,2.3,6.3,2,6.3z",
      fill: props.fill,
      stroke: props.stroke,
      strokeWidth: props.strokeWidth
    }),
    viewBox: "0 0 12 8",
    xmlns: "http://www.w3.org/2000/svg",
    xmlnsXlink: "http://www.w3.org/1999/xlink"
  });
}

let Tilde = {
  make: Icon$Tilde
};

function Icon(props) {
  let card = props.card;
  let match = getFillAttrs(card);
  let strokeWidth = match.strokeWidth;
  let stroke = match.stroke;
  let fill = match.fill;
  let match$1 = card.shape;
  switch (match$1) {
    case "Tilde" :
      return JsxRuntime.jsx(Icon$Tilde, {
        fill: fill,
        stroke: stroke,
        strokeWidth: strokeWidth
      });
    case "Diamond" :
      return JsxRuntime.jsx(Icon$Diamond, {
        fill: fill,
        stroke: stroke,
        strokeWidth: strokeWidth
      });
    case "Pill" :
      return JsxRuntime.jsx(Icon$Pill, {
        fill: fill,
        stroke: stroke,
        strokeWidth: strokeWidth
      });
  }
}

function Icon$Patterns(props) {
  let colors = [
    "Red",
    "Green",
    "Purple"
  ];
  return JsxRuntime.jsx("defs", {
    children: Belt_Array.map(colors, color => {
      let patternId = "stripes-" + colorToString(color);
      let colorValue = getColorValue(color);
      return JsxRuntime.jsxs("pattern", {
        children: [
          JsxRuntime.jsx("line", {
            x1: "1",
            x2: "1",
            y1: "0",
            y2: "8"
          }),
          JsxRuntime.jsx("line", {
            x1: "2.2",
            x2: "2.2",
            y1: "0",
            y2: "8"
          }),
          JsxRuntime.jsx("line", {
            x1: "3.5",
            x2: "3.5",
            y1: "0",
            y2: "8"
          }),
          JsxRuntime.jsx("line", {
            x1: "4.8",
            x2: "4.8",
            y1: "0",
            y2: "8"
          }),
          JsxRuntime.jsx("line", {
            x1: "6",
            x2: "6",
            y1: "0",
            y2: "8"
          }),
          JsxRuntime.jsx("line", {
            x1: "7.2",
            x2: "7.2",
            y1: "0",
            y2: "8"
          }),
          JsxRuntime.jsx("line", {
            x1: "8.5",
            x2: "8.5",
            y1: "0",
            y2: "8"
          }),
          JsxRuntime.jsx("line", {
            x1: "9.8",
            x2: "9.8",
            y1: "0",
            y2: "8"
          }),
          JsxRuntime.jsx("line", {
            x1: "11",
            x2: "11",
            y1: "0",
            y2: "8"
          })
        ],
        id: patternId,
        height: "8",
        width: "12",
        patternUnits: "userSpaceOnUse",
        stroke: colorValue,
        strokeWidth: "0.3",
        x: "0"
      }, patternId);
    })
  });
}

let Patterns = {
  make: Icon$Patterns
};

let make = Icon;

export {
  getColorValue,
  getColor,
  colorToString,
  getPatternId,
  getFillAttrs,
  Diamond,
  Pill,
  Tilde,
  make,
  Patterns,
}
/* react/jsx-runtime Not a pure module */
