// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function initiateTimeout(setter, onDecrement) {
  let timeout = setTimeout(() => setter(prev => {
    let newValue = prev !== undefined && prev !== 0 ? Stdlib_Option.map(prev, a => a - 1 | 0) : undefined;
    onDecrement(newValue);
    return newValue;
  }), 1000);
  return () => {
    clearTimeout(timeout);
  };
}

function useCountdown(totalTime, setter, onDecrement) {
  React.useEffect(() => {
    if (totalTime !== undefined && totalTime !== 0) {
      initiateTimeout(setter, onDecrement);
    }
    return () => setter(param => {});
  }, [
    totalTime,
    setter
  ]);
  return totalTime;
}

export {
  initiateTimeout,
  useCountdown,
}
/* react Not a pure module */
