// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function useCountdown(totalTime, setter, onDecrement) {
  React.useEffect(() => {
    if (typeof totalTime !== "object") {
      return;
    } else {
      let timeout = setTimeout(() => setter(prev => {
        let newValue;
        if (typeof prev !== "object") {
          newValue = "Stopped";
        } else {
          let x = prev._0;
          newValue = x !== 0 ? ({
              TAG: "Count",
              _0: x - 1 | 0
            }) : "Ending";
        }
        onDecrement(newValue);
        return newValue;
      }), 1000);
      return () => {
        clearTimeout(timeout);
      };
    }
  }, [
    totalTime,
    setter,
    onDecrement
  ]);
  return totalTime;
}

export {
  useCountdown,
}
/* react Not a pure module */
