// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "../engine/Icon.res.mjs";
import * as React from "react";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Nullable from "@rescript/runtime/lib/es6/Stdlib_Nullable.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function showBoardState(state) {
  switch (state) {
    case "Initializing" :
      return "Initializing";
    case "Active" :
      return "Active";
    case "Disabled" :
      return "Disabled";
    case "Selecting" :
      return "Selecting";
  }
}

let hasChildren = (function hasChildren(element) { 
  console.log("element", element)
  return element.hasChildNodes() 
});

function Board$Render(props) {
  let match = React.useState(() => "Initializing");
  let setBoardState = match[1];
  let boardState = match[0];
  let boardRef = React.useRef(null);
  React.useLayoutEffect(() => {
    let boardElement = boardRef.current;
    let hasCards = Stdlib_Nullable.getOr(Stdlib_Nullable.map(boardElement, element => hasChildren(element)), false);
    if (hasCards) {
      setBoardState(param => "Active");
    }
    return () => setBoardState(param => "Disabled");
  }, []);
  console.log("boardState", boardState);
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
    children: [
      JsxRuntime.jsx("p", {
        children: showBoardState(boardState)
      }),
      JsxRuntime.jsx("article", {
        children: Belt_Array.map(props.deck, card => JsxRuntime.jsx(Icon.make, {
          card: card
        }, card.id.toString())),
        ref: Primitive_option.some(boardRef),
        className: "grid grid-cols-3 gap-6"
      })
    ]
  });
}

let Render = {
  make: Board$Render
};

export {
  showBoardState,
  hasChildren,
  Render,
}
/* Icon Not a pure module */
