// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function showBoardState(state) {
  switch (state) {
    case "Active" :
      return "Active";
    case "Disabled" :
      return "Disabled";
    case "Selecting" :
      return "Selecting";
  }
}

function Board$Render(props) {
  let match = React.useState(() => "Active");
  return JsxRuntime.jsx("article", {
    children: JsxRuntime.jsx("p", {
      children: showBoardState(match[0])
    }),
    className: "grid grid-cols-3 gap-6"
  });
}

let Render = {
  make: Board$Render
};

export {
  showBoardState,
  Render,
}
/* react Not a pure module */
