// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "../engine/Icon.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Card(props) {
  return JsxRuntime.jsx("article", {
    children: JsxRuntime.jsx(Icon.make, {
      card: props.card
    }),
    className: "flex flex-col items-center justify-between p-2 border-2 border-gray-300 rounded-md"
  });
}

let make = Card;

export {
  make,
}
/* Icon Not a pure module */
