// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function toShape(n) {
  if (n !== 1) {
    if (n !== 2) {
      return "Pill";
    } else {
      return "Diamond";
    }
  } else {
    return "Tilde";
  }
}

function toColor(n) {
  if (n !== 1) {
    if (n !== 2) {
      return "Purple";
    } else {
      return "Green";
    }
  } else {
    return "Red";
  }
}

function toFill(n) {
  if (n !== 1) {
    if (n !== 2) {
      return "Outlined";
    } else {
      return "Striped";
    }
  } else {
    return "Solid";
  }
}

function toNumber(n) {
  if (n !== 1) {
    if (n !== 2) {
      return "Three";
    } else {
      return "Two";
    }
  } else {
    return "One";
  }
}

function Card$Render$Diamond(props) {
  return JsxRuntime.jsx("svg", {
    children: JsxRuntime.jsx("polygon", {
      points: "1,4 6,7 11,4 6,1 "
    }),
    id: "diamond",
    viewBox: "0 0 12 8",
    xmlns: "http://www.w3.org/2000/svg",
    xmlnsXlink: "http://www.w3.org/1999/xlink"
  });
}

let Diamond = {
  make: Card$Render$Diamond
};

function Card$Render$Pill(props) {
  return JsxRuntime.jsx("svg", {
    children: JsxRuntime.jsx("path", {
      d: "M3,2h6c1.1,0,2,0.9,2,2v0c0,1.1-0.9,2-2,2H3C1.9,6,1,5.1,1,4v0C1,2.9,1.9,2,3,2z"
    }),
    id: "pill",
    viewBox: "0 0 12 8",
    xmlns: "http://www.w3.org/2000/svg",
    xmlnsXlink: "http://www.w3.org/1999/xlink"
  });
}

let Pill = {
  make: Card$Render$Pill
};

function Card$Render$Tilde(props) {
  return JsxRuntime.jsx("svg", {
    children: JsxRuntime.jsx("path", {
      d: "M2,6.3C1.4,6.3,0.9,6,0.5,5.5C0,4.7,0.2,3.6,1,3c1.9-1.3,4-1.7,6-0.6c0.7,0.4,1.3,0.2,1.9-0.3c0.7-0.6,1.8-0.5,2.5,0.2\n                  c0.6,0.7,0.5,1.8-0.2,2.5C9.4,6.3,7.3,6.6,5.3,5.5C4.5,5.1,3.7,5.4,3,6C2.7,6.2,2.3,6.3,2,6.3z"
    }),
    id: "tilde",
    viewBox: "0 0 12 8",
    xmlns: "http://www.w3.org/2000/svg",
    xmlnsXlink: "http://www.w3.org/1999/xlink"
  });
}

let Tilde = {
  make: Card$Render$Tilde
};

let Render = {
  Diamond: Diamond,
  Pill: Pill,
  Tilde: Tilde
};

export {
  toShape,
  toColor,
  toFill,
  toNumber,
  Render,
}
/* react/jsx-runtime Not a pure module */
