// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "./Card.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

function init() {
  let cards = Belt_Array.makeBy(81, param => ({
    id: 0,
    shape: "Tilde",
    color: "Red",
    fill: "Solid",
    number: "One"
  }));
  let cardId = 0;
  for (let shape = 1; shape <= 3; ++shape) {
    for (let color = 1; color <= 3; ++color) {
      for (let number = 1; number <= 3; ++number) {
        for (let fill = 1; fill <= 3; ++fill) {
          cards[cardId] = {
            id: cardId,
            shape: Card.toShape(shape),
            color: Card.toColor(color),
            fill: Card.toFill(fill),
            number: Card.toNumber(number)
          };
          cardId = cardId + 1 | 0;
        }
      }
    }
  }
  return cards;
}

export {
  init,
}
/* Card Not a pure module */
