// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as CallSetButton from "./engine/CallSetButton.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import ViteSvg from "./assets/vite.svg";
import * as JsxRuntime from "react/jsx-runtime";
import RescriptLogoSvg from "./assets/rescript-logo.svg";

function make() {
  return JsxRuntime.jsx("p", {
    children: "YEET!",
    className: "text-2xl m-16 font-semibold text-center"
  });
}

function App(props) {
  let match = React.useState(() => {});
  let setYeet = match[1];
  let handleClick = param => setYeet(param => make());
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "Set game",
        className: "text-6xl m-16 font-semibold text-center"
      }),
      JsxRuntime.jsx("h2", {
        children: Stdlib_Option.getOr(match[0], null),
        className: "text-2xl m-16 font-semibold text-center"
      }),
      JsxRuntime.jsx(CallSetButton.make, {
        text: "SET!",
        onClick: handleClick
      })
    ],
    className: "max-w-200"
  });
}

let make$1 = App;

export {
  make$1 as make,
}
/*  Not a pure module */
