// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Deck from "./play/Deck.res.mjs";
import * as Rules from "./rules/Rules.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function make() {
  let deck = Belt_Array.shuffle(Deck.init());
  console.log("Deck", deck);
  let cards = deck.slice(0, 3);
  Stdlib_Array.reduce([
    0,
    1,
    2
  ], Rules.GameSet.make(), (set, i) => {
    let __x = Rules.GameSet.maybeSet(set);
    console.log("Status", __x);
    let s = Rules.GameSet.add(set, Stdlib_Option.getOrThrow(cards[i], undefined));
    let status = Rules.GameSet.maybeSet(s);
    if (typeof status !== "object") {
      console.log("Set empty");
    } else if (status.TAG === "Filling") {
      console.log("Set filling", status._0);
    } else {
      console.log("Set filled", status._0);
    }
    return s;
  });
  let listCards = Stdlib_List.fromArray(cards);
  let checkFns = [
    [
      "Shapes",
      Rules.GameSet.checkShapes
    ],
    [
      "Colors",
      Rules.GameSet.checkColors
    ],
    [
      "Fills",
      Rules.GameSet.checkFills
    ],
    [
      "Numbers",
      Rules.GameSet.checkNumbers
    ]
  ];
  checkFns.map(param => [
    param[0],
    param[1](listCards)
  ]).forEach(param => {
    console.log("Check", param[0], param[1]);
  });
}

export {
  make,
}
/* Deck Not a pure module */
